### ISSUE TITLE
sensor.pvpc unavailable since some time ago

### ISSUE THREAD

**Issue by oscarpuigcerver** [danimart1991/pvpc-hourly-pricing-card#62]
Since some time ago, pvpc sensor appears as unavailable and the log shows:
```
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/pvpc_hourly_pricing/__init__.py:102
Integration: Spain electricity hourly pricing (PVPC)
First occurred: 1:01:41 PM (1 occurrences)
Last logged: 1:01:41 PM

Error setting up entry PVPC for pvpc_hourly_pricing
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 390, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/pvpc_hourly_pricing/__init__.py", line 102, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
```
I'm using the latest version of the pvpc card (1.9.0)

**Comment by danimart1991** [comment]
Hello @oscarpuigcerver 

PVPC Sensor is not related to the card. It is a native sensor and must be issued in [the official Home Assistant Core repository](https://github.com/home-assistant/core).
